version: "3"
services:
  server:
    image: controleback:latest
    build:
      context: .
    restart: on-failure
    container_name: appcontrole
    ports:
      - 8091:8091
    depends_on:
      - dbcontrole
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbcontrole:3306/backcontrolefacile?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&maxAllowedPacket=52428800
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=1234
      
  dbcontrole:
    image: mariadb:10.4.27
    command: --max_allowed_packet=3250585
    container_name: dbcontrole
    restart: always
    ports:
      - 3310:3310
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=backcontrolefacile
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
  phpmyadmincontrole:
    image: phpmyadmin/phpmyadmin
    container_name: pmacontrole
    links:
      - dbcontrole
    environment:
      PMA_HOST: dbcontrole
      # PMA_PORT: 3307
      # PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8999:80

volumes:
  db_data:

